### ISSUE TITLE
reconnect your android device to the rc for full functionality

### ISSUE THREAD

**Issue by causalloop** [diux-dev/rosettadrone#26]
I'm getting the message "reconnect your android device to the rc for full functionality" in the app - though it does indicate that its connected to the aircraft.  Obviously re-connecting isn't doing the job, but I'm wondering if its the version of Android I'm on - I tried on my Pixel 3XL which is on 9 (Pie) and on my nVidia Shield K1 which is on 7.0 (Nougat).  Unfortunately I don't have anything on 8, and nVidia is apparently not going to be updating their shield tablets.

On the Pixel, the app doesn't even open, it crashes immediately.  On the shield, it opens, gives the aforementioned message when connected and the QGC app doesn't seem to load (just hangs).  

_Should_ this work on 7 or 9, or is the 'expected to work platform' only 8.x?

**Comment by sjd69** [comment]
What drone are you using?

The current version of the SDK that's in use does not work with Android Pie.

On Dec 25, 2018 6:55 PM, causalloop <notifications@github.com> wrote:

I'm getting the message "reconnect your android device to the rc for full functionality" in the app - though it does indicate that its connected to the aircraft. Obviously re-connecting isn't doing the job, but I'm wondering if its the version of Android I'm on - I tried on my Pixel 3XL which is on 9 (Pie) and on my nVidia Shield K1 which is on 7.0 (Nougat). Unfortunately I don't have anything on 8, and nVidia is apparently not going to be updating their shield tablets.

On the Pixel, the app doesn't even open, it crashes immediately. On the shield, it opens, gives the aforementioned message when connected and the QGC app doesn't seem to load (just hangs).

Should this work on 7 or 9, or is the 'expected to work platform' only 8.x?

**Comment by causalloop** [comment]
Bah, I knew I was going to forget that..

It's a mavic 2 pro.

Does it run on Nougat?

**Comment by sjd69** [comment]
The current version only supports up to the p4pv2 unfortunately. If you try to connect an unsupportive drone you'll receive those please reconnect rc messages. I believe SDK 4.7 adds support for the Mavic 2 platform.

On Dec 25, 2018 8:53 PM, causalloop <notifications@github.com> wrote:
Bah, I knew I was going to forget that..

It's a mavic 2 pro.

Does it run on Nougat?

**Comment by causalloop** [comment]
Oh.. dang- you're right (now that I'm looking a bit closer..)  Sorry bout that.  :-/
