### ISSUE TITLE
DJI Phantom 2 Support?

### ISSUE THREAD

**Issue by trick-1** [diux-dev/rosettadrone#33]
Hi There

This may not be an issue but rather by design, lack of functionality, etc....or plain just not supported :-/

Trying to get rosettadrone to work with a DJI Phantom 2 

When I connect the DJI Remote and start Rosetta Drone v0.5 I get 

_Not ready to execute mission
NOT_SUPPORTED_

in the DJI tab.

thanks in advance....

Richard

**Comment by sjd69** [comment]
Unfortunately that platform isn't supported by DJI's SDK and therefore not supported in RosettaDrone either.
