### ISSUE TITLE
Infinite "Drone connecting..." error

### ISSUE THREAD

**Issue by jacobsenmd** [diux-dev/rosettadrone#4]
Sometimes the DJI SDK detects a connected drone, but all the components (flight controller, RC controller, battery, etc.) are null. We believe this may be a bug in the DJI SDK (https://github.com/dji-sdk/Mobile-SDK-Android/issues/280.

To clear the error, restart the drone, kill the app, and restart it. If that does not fix the issue, uninstall and then reinstall the app.

**Comment by Djacob502** [comment]
I think this might be a bug related to the mavic series. I have not seen this with the phantom or m200 series. Also, if you might want to try the crystal sky if you have access to one. I find the crystal sky connects better than a standard android tablet.
