### ISSUE TITLE
Rosetta Drone

### ISSUE THREAD

**Issue by kripper** [diux-dev/rosettadrone#40]
Hi, we are actively maintaining Rosetta Drone.

We have added Mini support, a MissionManager with VirtualSticks, MAVLink 2 support, fixed bugs, etc.
Can you please link to the active repo on your README?
https://github.com/The1only/rosettadrone

**Comment by markdjacobsen** [comment]
Done! Thanks for keeping this alive!

**Comment by kripper** [comment]
Thanks.
